### ISSUE TITLE
\aliyun\sdk\Aliyun 这个文件composer下载怎么没有呢？

### ISSUE THREAD

**Issue by pionear-layen** [AxiosCros/aliyun-sdk#1]
用你的example ，一直提示
array(5) {
  ["Recommend"] => string(91) "https://error-center.aliyun.com/status/search?Keyword=InvalidTimeStamp.Expired&source=PopGw"
  ["Message"] => string(46) "Specified time stamp or date value is expired."
  ["RequestId"] => string(36) "A982A6AF-4FFB-4D6B-A9E1-A34A23CDF59E"
  ["HostId"] => string(19) "alidns.aliyuncs.com"
  ["Code"] => string(24) "InvalidTimeStamp.Expired"
}

**Comment by AxiosLeo** [comment]
你调接口的客户端的时间戳 跟 阿里云服务端的时间戳差别太大，过期了。

**Comment by AxiosLeo** [comment]
在Message和Code里不是写的很清楚了么。 InvalidTimeStamp.Expired 意思就是"无效的时间戳.过期"

**Comment by pionear-layen** [comment]
提示的内容我知道，就是不知道哪里调用，我是直接复制你的example
 
        \aliyun\sdk\Aliyun::auth($access_id,$access_secret);
        \aliyun\sdk\Aliyun::region('cn-hangzhou');
        $request = \aliyun\sdk\alidns\AlidnsClient::action("DescribeDomains");
        $request->setParam("PageNumber",1);
        $request->setParam("PageSize",15);
        $request->setParam("KeyWord","com");
        $response = $request->request();
        dump($response->getContent());

**Comment by AxiosLeo** [comment]
我是调的系统时间，你在执行这段代码前，先看一下系统时间是多少，再看看实际的时间应该是多少。

* 查看时间
```php
date("Y-m-d\TH:i:s\Z")
```

* 手动设置时间
```php
$request->setParam("Timestamp", date("Y-m-d\TH:i:s\Z",$timestamp));
```

**Comment by pionear-layen** [comment]
可能我用docker容器运行的关系，所以时间对不上。我试下

**Comment by AxiosLeo** [comment]
好像容器在run的时候，可以设置跟host时间一致的

**Comment by pionear-layen** [comment]
容器时间设置一致了，还是提示这个错误。我设置了
$request->setParam("Timestamp", date("Y-m-d\TH:i:s\Z",time()));
用这个也不行

**Comment by AxiosLeo** [comment]
@layen520  那就是时区的问题了。
看来你没有执行 `date("Y-m-d\TH:i:s\Z",)` 看下具体的日期是多少。
另外`date("Y-m-d\TH:i:s\Z",time())` 这句 和`date("Y-m-d\TH:i:s\Z")` 是没区别的，这么写有何意义呢。

罢了，稍后我加上时区的默认设置，再发个版本吧。

**Comment by pionear-layen** [comment]
用了你最新的版本还是这个问题提示，你是用的什么环境呢和框架呢？

**Comment by pionear-layen** [comment]
用了这种写法好了。。$request->setParam("Timestamp", gmdate('Y-m-d\TH:i:s\Z'));

**Comment by AxiosLeo** [comment]
@layen520  
那很奇怪诶。
我这里，`date("Y-m-d\TH:i:s\Z")` 和 `gmdate('Y-m-d\TH:i:s\Z')` ，结果是一模一样的。。。
你能发下你这两个方法运行的结果么，我想看下差在哪里。

**Comment by pionear-layen** [comment]
date的就是InvalidTimeStamp.Expired 
gmdate我是参考了官方的SDK看到官方这样写 我就这样写了

**Comment by AxiosLeo** [comment]
不是，我是说你echo或者var_dump下他们输出的值，不是访问接口的回调结果。

这个回调结果只能说明时间有问题，看不出其它信息。

但是你能发一下date函数和gmdate函数的输出结果，就大概能知道差在哪里了。

**Comment by AxiosLeo** [comment]
我改下时区这两个函数的结果就不同了。
gmdate应该用的是格林尼治标准时间。
一会儿我改下代码，统一用gmdate 生成时间，然后再发哥版本。

**Comment by pionear-layen** [comment]
我明天上班才能打印哈，机器环境不同。
