### ISSUE TITLE
Readme里的省略号是几个意思？

### ISSUE THREAD

**Issue by MukuroSama** [AxiosCros/aliyun-sdk#4]
作为一个功能并不全面的，第三方的SDK，能不能好好地把你们已支持的功能列出来？如果我要用的功能没支持，那我就不用了。

**Comment by AxiosLeo** [comment]
@MukuroSama   目前仅支持一些主流的服务

省略号代表还没开发完的那些服务，已开发的都列出来了。
如果你要用的服务我这个sdk里不支持，可以选择用官方版的，或者提需求，我有空的话添加进去。
当然，最好的是您能一起贡献代码。sdk的核心组件基本开发完了，剩下的功能，只要继承核心类，模仿着已有的组件开发就好了。

另外，我这个是支持自定义扩展的，详细的可以看 “Customized Request” 这部分里写的
